name: traidbiz_seller
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # icons
  cupertino_icons: ^1.0.5
  flutter_phosphor_icons: ^0.0.1+6
  # font_awesome_flutter: ^9.2.0

  # core
  connectivity: ^3.0.6
  # permission_handler: ^8.3.0

  # ui
  responsive_framework: ^0.2.0
  form_field_validator: ^1.1.0
  loading_overlay: ^0.3.0
  syncfusion_flutter_charts: ^20.1.59
  expandable: ^5.0.1

  # state management
  get: ^4.6.5

  # files, images & player
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  flutter_svg: ^1.1.0
  lottie: ^1.3.0
  youtube_player_flutter: ^8.1.0

  # code generator
  freezed_annotation: ^2.0.3

  # data
  dio: ^4.0.6
  get_storage: ^2.0.3

  # others
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.2
  device_info: ^2.0.3
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^12.0.4
  fluttertoast: ^8.0.9
  overlay_support: ^2.0.1
  country_pickers:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  intl: ^0.17.0
  json_serializable:
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  build_runner:

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/app/launcher_icon.png"
#  adaptive_icon_background: "assets/app/launcher_icon.png"
#  adaptive_icon_foreground: "assets/app/launcher_icon.png"
#  # === Generate Launcher Icon ===
#  #flutter pub get
#  #flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app/
    - assets/images/
    - assets/icons/
