// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBOjIucc8kSph9DJxcv9ZZf68mpdwBd-s',
    appId: '1:961065025807:android:e7a738393280557c15be7a',
    messagingSenderId: '961065025807',
    projectId: 'traidbiz-seller',
    storageBucket: 'traidbiz-seller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEy6-d7ZzcpDFCjhigmYki3oQKQhuJ_3M',
    appId: '1:961065025807:ios:daaba1a119b24fe915be7a',
    messagingSenderId: '961065025807',
    projectId: 'traidbiz-seller',
    storageBucket: 'traidbiz-seller.appspot.com',
    iosClientId:
        '961065025807-rbr8napgum1mv37m81tjunv4sunsf767.apps.googleusercontent.com',
    iosBundleId: 'com.eoxysit.traidbizseller',
  );
}
